function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 12-May-2016 15:27:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',20,'YTickLabel','');


%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 360]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',4);
set(plot1(1),'Color',[0 0 0]);

% Create xlabel
xlabel('Longitude','FontSize',22);

% Create ylabel
ylabel('Density','FontSize',22);

% Create textbox
annotation(figure1,'textbox',...
    [0.430395530395527 0.461904761904764 0.186362711362716 0.0714285714285883],...
    'Color',[0.850980392156863 0.325490196078431 0.0980392156862745],...
    'String','Average density',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',11,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.574626299626298 0.811904761904766 0.186362711362716 0.0714285714285885],...
    'String','Density variation',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',11,...
    'FitBoxToText','off');

